#! /bin/sh

# Logging
# set -xv
# exec 2>>/tmp/bspwm.log

# Start Compositor
if ! pgrep -x "picom" >/dev/null
then
    picom --config "$HOME/.config/picom.conf" -b &
fi

# Keybord local
# setxkbmap -layout de -variant nodeadkeys -option terminate:ctrl_alt_bksp &

# Java fuckery ( Roger<3 )
wmname compiz &

# Show Coursor
xsetroot -cursor_name left_ptr

# Keybord shortcuts
killall -e sxhkd; \
sxhkd > /tmp/sxhkd.log 2>&1 &


# Connect 2nd Monitor
$HOME/.config/bspwm/hdmi.sh 

# Init bspwm, only init monitors on first load
if [[ "$1" = 0 ]]; then
    bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 text code browser notes mail
fi

# Border Style
bspc config border_width         0
bspc config window_gap          12

# Config
bspc config split_ratio                0.52
bspc config borderless_monocle         true
bspc config gapless_monocle            true
bspc config single_monocle	       true
bspc config top_monocle_padding        0
bspc config bottom_monocle_padding     0
bspc config bottom_padding             0
bspc config top_padding                0
bspc config -m eDP-1 top_padding       25
bspc config focus_follows_pointer      true
bspc config remove_disabled_monitors   true
#bspc config merge_overlapping_monitors true

# Mouse Movement
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

# Window Rules
# Get Window class with:
#   xprop WM_CLASS
bspc rule -a Screenkey manage=off
bspc rule -a firefox border=off desktop="browser" follow=on
bspc rule -a zen border=off desktop="browser" follow=on
bspc rule -a obsidian desktop="notes" follow=on focus=on
bspc rule -a Code desktop="code" follow=on focus=on
bspc rule -a Sylpheed desktop="mail" follow=off focus=off
bspc rule -a thunderbird desktop="mail" follow=off focus=off
bspc rule -a discord desktop="text" follow=on focus=on
bspc rule -a WebCord desktop="text" follow=on focus=on
bspc rule -a Zathura state=tiled
bspc rule -a Xfce4-appfinder state=floating
bspc rule -a "Toggl Desktop" state=floating
bspc rule -a "Nm-connection-editor" state=floating
bspc rule -a paradiso state=floating


# Restart Polybar
$HOME/.config/polybar/launch.sh &


# Load Background
# nitrogen --random --set-zoom-fill &
# systemctl start --user wallpaper
# systemctl restart --user roger &
# Apply last use background
$HOME/.fehbg &



# Polkit Authentication
#if ! pgrep -x "polkit-kde-authentication-agent-1" >/dev/null
#then
#    /usr/lib/polkit-kde-authentication-agent-1 &
#fi
#if ! pgrep -x "polkit-gnome-authentication-agent-1" >/dev/null
#then
#    /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#fi

# Start Dunst Notifications
if ! pgrep -x "dunst" >/dev/null
then
    dunst &
fi

# Lock screen
if ! pgrep -x "xss-lock" >/dev/null
then
	xss-lock --transfer-sleep-lock -- i3lock --nofork -c 333333FF -k --composite --wrong-text="Fuck off" --verif-text="Hmmm" -f -e &
    # xss-lock -- env XSECURELOCK_FONT='Hack Nerd Font Mono:style=Bold' XSECURELOCK_SHOW_DATETIME='1' xsecurelock &
fi


# Start blueman
#if ! pgrep -x "blueman-applet" >/dev/null
#then
#    blueman-applet &
#fi

# Start nm-applet
#if ! pgrep -x "nm-applet" >/dev/null
#then
#    nm-applet &
#fi

# Start Automounting with udiskie
if ! pgrep -x "udiskie" >/dev/null
then
    udiskie &
fi

# Start Thunderbird
if ! pgrep -x "thunderbird" >/dev/null
then
    thunderbird &
fi

# Start Sylpheed
#if ! pgrep -x "sylpheed" >/dev/null
#then
   #  sylpheed &
#fi

# Start Neo layout overlay
if ! pgrep -f "neo_layout_viewer" >/dev/null
then
	neo_layout_viewer &
fi



# Enviorment for vscode
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
