wallpaper_directory = "~/wallpapers/"
interval = 400
history_length = 25
mode = "Random"
wallpaper_change_command = "swww img --transition-type fade --transition-duration 3 --transition-step 1 --transition-fps 120 %wallpaper%"
